### ISSUE TITLE
MV Bot is Offline

### ISSUE THREAD

**Issue by scampa123** [tmanifold/mvbot#12]
It seems the MV bot is offline today.  Is there anything I can do on my end or is it just on yours?

**Comment by tmanifold** [comment]
Thanks for letting me know! I have a lead on why this is happening and am looking into it. In the mean time i'm restarting the bot

**Comment by juanjotoronja** [comment]
Bot is offline

**Comment by tmanifold** [comment]
apologies. I've restarted the bot and modified the server restart schedule
to be more frequent until i can get the new version out.
