### ISSUE TITLE
Show original author name

### ISSUE THREAD

**Issue by fransyozef** [tmanifold/mvbot#16]
First, awesome feature!!! Can't believe Discord doesn't have this :(

I tried it, the message was moved. But the new message doesn't show the original author name.

To be clear, I moved it , not the original author of the message.

**Comment by tmanifold** [comment]
If I understand you correctly, the message is moved to the new channel, but the author of the original message is not mentioned, is that correct? Could you provide a screenshot showing what you are describing?

**Comment by fransyozef** [comment]
hmm

the first time I got

```
<@null> | #bug-report
Mon Apr 19 2021 09:07:21 GMT+0000 (Coordinated Universal Time)
```
But now I tried again , and it worked


```
@fransyozef_rollerskate_app | #bug-report
Tue Apr 20 2021 18:46:07 GMT+0000 (Coordinated Universal Time)
```

**Comment by tmanifold** [comment]
Other users have reported this issue as well. I suspect this may have to do with the way the discord library handles caching of users. Was it by chance a new server or a user new to the server?

This is something I'm tentatively looking into, but am as of yet unsure if it is something I can resolve on my end or a problem with discord.
