### ISSUE TITLE
[improvement] more friendly text

### ISSUE THREAD

**Issue by fransyozef** [tmanifold/mvbot#17]
Right now you have something like

```
@originalAuthor | #original-channel
Tue Apr 20 2021 18:46:07 GMT+0000 (Coordinated Universal Time)
@moderatorUser

Some text
```

I propose something more friendly like

```
This message was moved by @moderatorUser from channel #original-channel
@originalAuthor said 

Some text

```

**Comment by tmanifold** [comment]
Thanks for the suggestion! It turns out that I have something similar planned for the next update, but I like your format so will likely implement something similar
