### ISSUE TITLE
when I move it doesn't carry the original user who created the post

### ISSUE THREAD

**Issue by lucianahanan** [tmanifold/mvbot#18]
instead, it puts a @null, where I expected to be the original user poster @name.

Also, it puts that tue may 11 string that it's just uggly, I'd rather not have the GMT part, at least.

<@null> | #chat
Tue May 11 2021 13:12:31 GMT+0000 (Coordinated Universal Time)
 - @Luciana

**Comment by tmanifold** [comment]
Please see #10 
Is the server new? Is the bot new to the server? is the original user new to the server? I am still working out whether or not if this is an issue with the discord.js library and the way it handles caching of users or if it is something I can actually fix on my end.
