### ISSUE TITLE
Bot is offline and not responding 

### ISSUE THREAD

**Issue by Aturner1986** [tmanifold/mvbot#23]
Title

**Comment by tmanifold** [comment]
Apologies. I should have this resolved in the next release, but am unsure
of when it will be live. I've restarted the server and the bot should be
back up soon.

**Comment by Aturner1986** [comment]
Thanks for the quick reply. Yeah I see the bot back online now :)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
