### ISSUE TITLE
Original user is showing up as @null

### ISSUE THREAD

**Issue by DorkyDino** [tmanifold/mvbot#26]
I looked through the closed issues and it looks like this issue has come up before, but it was supposed to be fixed. I've double checked my permissions and mvbot should be able to tag anyone, but it's only tagging @null for every post I move. 

I just invited mvbot today, and this is my first bot, so I may just be missing something! Let me know what I should do.

**Comment by DorkyDino** [comment]
I just noticed it will tag posts from me, but not from anyone else in Discord.

**Comment by tmanifold** [comment]
Is this issue still occuring? I have a hunch this this is related to how discordjs handles caching of users. Because users aren't cached explicitly at the time the bit joins the server, it may take some time before users are properly tagged.

**Comment by jmmelko** [comment]
Yes, I have the same issue.
Without this function, the bot is useless…

**Comment by tmanifold** [comment]
> Hi, Yes, I have the same issue. Without this function, the bot is useless…

Sorry for the inconvenience. Presently, I do not have the time to actively work on the bot and address this issue. However, you are more than welcome to fork the project and determine a solution.

**Comment by jmmelko** [comment]
Ok.
How do you push the code to an inevitable bot? Do I have to create an account on Top.gg?

**Comment by tmanifold** [comment]
> Ok but: How do I push my code to an invitable bot? Do I have to create an account on Top.gg?
> 
> Btw I am surprised by the line: `<@' + msg.member + '>`
> 
> * I would have expected msg.member.id, and not directly the member object
> * I would have expected author instead of member
> 
> is the Discord API manual here: https://discord.com/developers/docs/interactions/message-components

I actually don't remember why I wrote it this way, just that it worked. As for hosting a bot, check out the [Discord Developer Portal docs](https://discord.com/developers/docs/intro)

**Comment by jmmelko** [comment]
Ok,
I am no longer able to reproduce the bug.

Btw, I have noticed that the code in the main branch is no longer compatible with the newest versions of Discord.js
