### ISSUE TITLE
Original user isn't attributed

### ISSUE THREAD

**Issue by fsnk** [tmanifold/mvbot#5]
In the screenshots it looks like the original user should be attributed in the moved message, but when I move a message it attributes it to "@null":

mvbot Today at 13:48
<@null> | #general
Sun Jan 10 2021 12:48:41 GMT+0000 (Coordinated Universal Time)
"Message moved to #food" - @fsnk

| Message content

**Comment by tmanifold** [comment]
Thanks for reporting this issue. Is this happening with the same user or multiple? Is this happening all the time or is it seemingly random?

**Comment by tmanifold** [comment]
I am unable to replicate this issue, and without more information won't be able address it.
