### ISSUE TITLE
Bot not move old posts

### ISSUE THREAD

**Issue by GR-noob** [tmanifold/mvbot#6]
Hello. First of all Crazy bot. I want to ask i do something wrong ?? If the post is new it move it without a problem but a old post it says "I was unable to find the message you want to move. Ensure you are entering a valid message ID." I have enabled to see old posts.

Thanks for your time

**Comment by tmanifold** [comment]
How old are the posts you are trying to move? are you referencing them by ID or by message link?

**Comment by GR-noob** [comment]
Hello and thank you for the reply. I think i am stupid. I tried to move a post from another channel to another channel (the post is in  public channel and i type !mv from admin only group channel to move a post from another public channel). But if i go first public channel and i type there !mv to move is working ok. I am just stupid sorry to bother you. And again great bot.

**Comment by tmanifold** [comment]
Currently the functionality only allows for moving a message from the same channel the !mv command is sent. Apologies if this wasn't clearly documented. On the future I may rework the bot to function as you expected.
