### ISSUE TITLE
Need help on using mvbot

### ISSUE THREAD

**Issue by LZDiscord** [tmanifold/mvbot#8]
I’m hoping you can help me out and be advised, I’ve just created my first Discord server. I’m extremely new at all this. I want to be able to move messages between channels and mvbot seems just what I need. I have imported it into my server (it shows up in the right hand pane of Discord). I don’t know how to use it though. Do I type some command in the same channel as the messages I want to move? The README page seems to show the command string !mv<message-Id><target-channel>[“reason”] . I figured out how to get the message ID for the message I want to move and I know what the target channel is. I e substituted what’s necessary but nothing happens.

**Comment by tmanifold** [comment]
You are correct that you need to type the command in the same channel as the message you want to move. An example command might look something like this: ```
!mv your-message-id-here #your-channel-here "your comment here"
```

Note that the comment is optional, but must be surrounded with quotation marks if included.

I'd you are still having issues, be sure to verify the bot has the necessary permissions, as specified in the readme. For information on how to update user permissions, refer to [this page](https://support.discord.com/hc/en-us/articles/206029707-How-do-I-set-up -Permissions-)
