### ISSUE TITLE
mvbot doesn't work

### ISSUE THREAD

**Issue by SwokDE** [tmanifold/mvbot#9]
Hello :)
I found your bot on my search how to move messages in discord.
I invited him and gave him all the necessary permissions and also enabled developer mode.

But it seems it doesn't work at all. I copied the message-id and used the command "!mv message-id I copied #area" (without "") but nothing happened. 
I tried the command in the channel where the original message is and also in the channel where the message should be move. 

I also noticed that the bot is offline. Could this be the reason why it doesn't work?

best regards,

swok

**Comment by tuqqo** [comment]
bot is offline, yes :-(

**Comment by tmanifold** [comment]
Sorry for this. Something is causing the bot to go offline now and then, but I have been too busy with university to focus on getting it fixed. In the meantime I have scheduled a job to restart the server hosting the bot once a month as a temporary fix. The bot should be up now. Sorry for the inconvenience and thank you for reporting the issue!
